from enum import Enum

class CancellationReason(str, Enum):
    CUSTOMER_CHANGED_MIND = "CUSTOMER_CHANGED_MIND"
    BIKE_UNAVAILABLE = "BIKE_UNAVAILABLE"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    ADMIN_CANCELLED = "ADMIN_CANCELLED"