"""Make bike user optional

Revision ID: 123a676e5207
Revises: 15b475789628
Create Date: 2026-05-09 17:18:43.398663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123a676e5207'
down_revision = '15b475789628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bikes', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bikes', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
