"""Add location_id to bikes

Revision ID: 621a0eb49fce
Revises: d818f39e9d29
Create Date: 2026-05-07 12:05:36.427535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621a0eb49fce'
down_revision = 'd818f39e9d29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bikes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'locations', ['location_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bikes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('location_id')

    # ### end Alembic commands ###
