"""add aadhar and licence columns to users

Revision ID: e618c42372f1
Revises: 621a0eb49fce
Create Date: 2026-05-09 01:10:36.363136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e618c42372f1'
down_revision = '621a0eb49fce'
branch_labels = None
depends_on = None


def upgrade():
    
    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_return_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aadhar', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('licence', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('licence')
        batch_op.drop_column('aadhar')

    with op.batch_alter_table('rentals', schema=None) as batch_op:
        batch_op.drop_column('expected_return_at')

    with op.batch_alter_table('bikes', schema=None) as batch_op:
        batch_op.alter_column('location_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
